apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  labels:
    app: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp
        image: wordpress
        ports:
        - containerPort: 80
        volumeMounts:
          - name: pv01
            mountPath: /var/www/html
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-svc
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MYSQL_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: MYSQL_PASSWORD
        - name: WORDPRESS_DB_NAME
          value: wp-db
        livenessProbe:
          httpGet:
            path: /
            port: 80 
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      initContainers:
      - name: init-container
        image: busybox
        command:
          ['sh', '-c', "until nslookup mysql-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mysql-svc; sleep 2; done"]          
      volumes:
      - name: pv02
        persistentVolumeClaim:
          claimName: db-vc         
      volumes:
      - name: pv01
        persistentVolumeClaim:
          claimName: wp-vc
          
